# Generated by Django 5.1.3 on 2025-09-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(),
        ),
    ]
